/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-04-05 05:12:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Code;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import assignment1.Course;
import java.util.ArrayList;

public final class Enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("assignment1.Course");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Enrollment</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/Code/Enroll_style.css\">\n");
      out.write("        <script src=\"/Code/alertHandler.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"topbar\" class=\"header\">\n");
      out.write("            <h1>Enrollment</h1>\n");
      out.write("            <div class=\"userinfo\">\n");
      out.write("                <span class=\"student\">Hi, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.givenNames}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.lastName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><!--get student name and student photo if available-->\n");
      out.write("                <img src=\"/images/student_photo.png\" alt=\"Student Photo\" class=\"studentphoto\">\n");
      out.write("                <a href=\"/Logout\" class=\"logout\">Log Out</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"enroll\">\n");
      out.write("            <div id=\"searchdisplay\">\n");
      out.write("                <b style=\"font-size: 30px;\">Current semester: ");
      out.print( session.getAttribute("semName"));
      out.write("</b>\n");
      out.write("                <div class=\"searchdiv\">\n");
      out.write("                    <input class=\"searchbar\" id=\"searchBar\">\n");
      out.write("                    <button class=\"searchbutton\" id=\"searchButton\" onclick=\"find(previousSibling.value)\">Search</button>\n");
      out.write("                </div>\n");
      out.write("            </div>  \n");
      out.write("            \n");
      out.write("            <form id=\"form_container\" action=\"/Enrollment\" method=\"post\">\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                ");
 ArrayList<Course> courses = (ArrayList<Course>) session.getAttribute("unfinishedCourses");
      out.write("\n");
      out.write("                ");
 if(courses !=null && !courses.isEmpty()){ 
      out.write("\n");
      out.write("                    <b style=\"font-size: 30px;\">Unfinished courses</b>\n");
      out.write("                    ");
 for(Course course : courses){ 
      out.write("\n");
      out.write("                        <div class=\"choices\">\n");
      out.write("                            <input type=\"checkbox\" id=\"");
      out.print(course.getCourseID());
      out.write("\" name=\"course[]\" value=\"");
      out.print(course.getCourseID());
      out.write("\" onclick=\"updateSelection(this)\">\n");
      out.write("                            <label for=\"");
      out.print(course.getCourseID());
      out.write('"');
      out.write('>');
      out.print(course.getCourseID());
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(course.getCourseName());
      out.write(" </label>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 }
      out.write("\n");
      out.write("                ");
}
      out.write("\n");
      out.write("\n");
      out.write("                <b style=\"font-size: 30px;\">Enrolled Courses</b>\n");
      out.write("                    ");
 ArrayList<String> finishedCourses = (ArrayList<String>) session.getAttribute("finishedCourses"); 
      out.write("\n");
      out.write("                    ");
 if (finishedCourses != null && !finishedCourses.isEmpty()) { 
      out.write("\n");
      out.write("                        <ul>\n");
      out.write("                            ");
 for (String finishedCourse : finishedCourses) { 
      out.write("\n");
      out.write("                                <li>");
      out.print( finishedCourse );
      out.write("</li>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <p>No enrolled courses.</p>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                \n");
      out.write("                <div id=\"submitregion\">\n");
      out.write("                    <div class=\"submitbox\">\n");
      out.write("                        <p>Currently choosing <span id=\"selectCourses\" style=\" display: none\"></span> </p>\n");
      out.write("                        <input type=\"submit\" value=\"Confirm\" class=\"submitbutton\" id=\"submit\" onclick=\"checkSelection()\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div><!-- add list of enroolled course, update message as to which course enrolled successfully, which one needs more course completed-->\n");
      out.write("\n");
      out.write("        <div id=\"alert\" class=\"alerthidden\">\n");
      out.write("        ");
 if(session.getAttribute("eMessage") !=null && (boolean) session.getAttribute("displayAlert")) {
      out.write("\n");
      out.write("            <script>\n");
      out.write("                console.log(\"block was run\")\n");
      out.write("                displayAlert();\n");
      out.write("            </script>\n");
      out.write("                <p style=\"color: rgb(0, 0, 164); font-size: 80%;\"> ");
      out.print(session.getAttribute("eMessage"));
      out.write("</p>\n");
      out.write("                <button onclick=\"hideAlert()\">Confirm</button>\n");
      out.write("            ");
session.setAttribute("displayAlert", false);
      out.write("\n");
      out.write("        ");
}else {
      out.write("\n");
      out.write("            <script>\n");
      out.write("                console.log(\"hidden was run\")\n");
      out.write("                hideAlert();\n");
      out.write("            </script>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
