/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-04-01 02:58:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Code;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import assignment1.Semester;
import java.util.ArrayList;

public final class ChoosingSem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("assignment1.Semester");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Choose your semester</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/Code/ChoosingSem_Style.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"topbar\" class=\"header\">\n");
      out.write("            <h1>Choose your semester</h1>\n");
      out.write("            <div class=\"userinfo\">\n");
      out.write("                <span class=\"student\">Hi, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.givenNames}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.lastName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><!--get student name and student photo if available-->\n");
      out.write("                <img src=\"/images/student_photo.png\" alt=\"Student Photo\" class=\"studentphoto\">\n");
      out.write("                <a href=\"/Logout\" class=\"logout\">Log Out</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"studentinfo\">\n");
      out.write("            <img src=\"student_photo.png\" alt=\"Student Photo\" class=\"studentphoto\">\n");
      out.write("            <div class=\"student_info_text\">\n");
      out.write("                <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.givenNames}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.lastName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\n");
      out.write("                <p>ID: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.stdNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("        <div id=\"form_container\">\n");
      out.write("            <b>Choosing Semester: </b>\n");
      out.write("            <form action=\"ChoosingSem\" method=\"post\">\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                ");
 ArrayList<Semester> semestersL =  (ArrayList<Semester>) session.getAttribute("semesters");
      out.write("\n");
      out.write("                ");
 if(semestersL !=null){ 
      out.write("\n");
      out.write("                    ");
for(Semester sem : semestersL){ 
      out.write("\n");
      out.write("                    ");
int index = sem.getSemester(); 
      out.write(" \n");
      out.write("                    ");
int year = sem.getYear(); 
      out.write("  \n");
      out.write("                    <div class=\"choices\">\n");
      out.write("                        <input type=\"radio\" id=\"Semester ");
      out.print(index);
      out.write(" year ");
      out.print(year);
      out.write("\" name=\"semester\" value=\"");
      out.print( sem.getSemesterID());
      out.write(" - Semester ");
      out.print(index);
      out.write(" year ");
      out.print(year);
      out.write("\" onclick=\"updateSelection(this)\">\n");
      out.write("                        <label for=\"Semester ");
      out.print(index);
      out.write(" year ");
      out.print(year);
      out.write("\">Semester ");
      out.print( sem.getSemester() );
      out.write(" Year ");
      out.print( sem.getYear());
      out.write(" </label> \n");
      out.write("                    </div>\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("                ");
}
      out.write("\n");
      out.write("                    \n");
      out.write("                <div id=\"submitregion\">\n");
      out.write("                    <div class=\"submitbox\">\n");
      out.write("                        <p>Currently choosing <span id=\"selectedSemester\" style=\" display: none\">none</span> </p>\n");
      out.write("                        <input type=\"submit\" value=\"Confirm\" class=\"submitbutton\" id=\"submit\" onclick=\"checkSelection()\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        function checkSelection(){\n");
      out.write("            if(document.getElementById(\"selectedSemester\").textContent ==\"none\"){\n");
      out.write("                alert(\"Please choose a semester before proceeding\");\n");
      out.write("                event.preventDefault();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function updateSelection(radio){\n");
      out.write("            const submitbutton = document.getElementsByClassName(\"submitbutton\")[0];\n");
      out.write("\n");
      out.write("            submitbutton.style.border = \"rgb(174, 44, 250) 1px solid\";\n");
      out.write("            submitbutton.style.backgroundColor = \"rgb(237, 218, 255)\";\n");
      out.write("            submitbutton.style.cursor = \"pointer\";\n");
      out.write("            document.getElementById(\"selectedSemester\").style.display = \"\";\n");
      out.write("            document.getElementById(\"selectedSemester\").textContent = radio.value;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
